apiVersion: v1
kind: Namespace
metadata:
  name: aaaaaa
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: crediticial-info
  namespace: aaaaaa
data:
  database: mongodb
  database_uri: mongodb://localhost:27017
  variable1: value1
  variable2: value2
  pass1: 124bsadhsd
---
apiVersion: v1
kind: Service
metadata:
    name: crediticial-info
    namespace: aaaaaa
spec:
    selector:
      app: crediticial-info
      tier: backend
    ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crediticial-info
  namespace: aaaaaa
spec:
  selector:
    matchLabels:
      app: crediticial-info
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: crediticial-info
        tier: backend
        track: stable
    spec:
      containers:
        - name: crediticial-info
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
          envFrom:
          - configMapRef:
              name: crediticial-info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        rewrite name crediticial-info.aaaaaa.com crediticial-info.aaaaaa.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
