---
apiVersion: v1
kind: Service
metadata:
    name: crediticial-info-client
    namespace: aaaaaa
spec:
    selector:
      app: crediticial-info-client
      tier: frontend
    ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crediticial-info-client
  namespace: aaaaaa
spec:
  selector:
    matchLabels:
      app: crediticial-info-client
      tier: frontend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: crediticial-info-client
        tier: frontend
        track: stable
    spec:
      containers:
        - name: crediticial-info-client
          image: "gcr.io/google-samples/hello-go-gke:1.0" ### EXAMPLE IMAGE
          ports:
            - name: http
              containerPort: 80
          env:
          - name: BACKEND_DNS
            value: crediticial-info.aaaaaa.com
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: aaaaaa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: crediticial-info-client.aaaaaa.mx
    http:
      paths:
      - path: /
        backend:
          serviceName: crediticial-info-client
          servicePort: 80
